name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger this action when there is a push to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use GitHub's hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use Node.js 16 (you can adjust this if necessary)

      - name: Install dependencies
        run: npm install
        working-directory: ./my-react-app

      - name: Build the app
        run: npm run build
        working-directory: ./my-react-app

      - name: Set Git user name and email
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
        working-directory: ./my-react-app  # Run in the `my-react-app` directory        

      - name: Deploy to GitHub Pages
        run: |
          npm install gh-pages --save-dev
          npm run deploy
        working-directory: ./my-react-app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # GitHub token for authentication